repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: check-executables-have-shebangs
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.270
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
